- name: Copy cert to clickhouse directory
  copy:
      src: "{{ server_cert_source }}"
      dest: "/etc/clickhouse-keeper/tls/server.crt"
      owner: clickhouse
      group: clickhouse
      remote_src: true
- name: Copy key to clickhouse directory
  copy:
      src: "{{ server_key_source }}"
      dest: "/etc/clickhouse-keeper/tls/server.key"
      owner: clickhouse
      group: clickhouse
      remote_src: true
- name: Change permission for server key
  file:
    path: "/etc/clickhouse-keeper/tls/server.key"
    mode: "0600"
- name: Copy CA to clickhouse directory
  copy:
      src: "{{ ca_cert_source }}"
      dest: "/etc/clickhouse-keeper/ca"
      owner: clickhouse
      group: clickhouse
      remote_src: true
- name: ca.crt 인증서를 신뢰하는 인증서로 등록
  copy:
      src: "{{ ca_cert_source }}"
      dest: "/etc/pki/ca-trust/source/anchors/"
      remote_src: true
- name: update ca
  shell: "update-ca-trust extract"
